version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./odoo_module:/mnt/extra-addons

  client_app:
    build: ./client_app
    depends_on:
      - odoo
    environment:
      - ODOO_URL=http://odoo:8069
      - ODOO_DB=mceasy
      - ODOO_USER=odoo
      - ODOO_PASS=odoo
    ports:
      - "5000:5000"

volumes:
  odoo-db-data: